//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by GUI.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_PROPERTYSHEETWITHLOGO_DIALOG 102
#define IDD_SETUPWIZARD_PPAGE_WAVE      102
#define IDD_GUI_PPAGE_FILES             102
#define IDS_BFF_TITLE                   102
#define IDD_SETUPWIZARD_DIALOG          103
#define IDD_GUI_DIALOG                  103
#define IDD_SETUPWIZARD_PPAGE_VOICE     104
#define IDD_GUI_PPAGE_MODULATION        104
#define IDD_SETUPWIZARD_PPAGE_SETUP     105
#define IDD_GUI_PPAGE_LINEAR            105
#define IDD_SETUPWIZARD_PPAGE_PERF      106
#define IDD_GUI_PPAGE_NONLINEAR         106
#define IDD_SETUPWIZARD_PPAGE_TIMBRE    107
#define IDD_GUI_PPAGE_OUTPUT            107
#define IDD_GUI_PPAGE_INFOS             108
#define IDD_GUI_PPAGE_FIRST             109
#define IDD_GUI_PPAGE_EXCITATION        110
#define IDR_MAINFRAME                   128
#define IDD_EDIT_SLIDEREX               129
#define IDD_GUI_DIALOG1                 130
#define IDB_BITMAP1                     131
#define IDD_FILTER_DIALOG               131
#define IDD_GUI_PPAGE_VISUAL            132
#define IDD_GUI_PPAGE_OTHER             132
#define IDB_TABIMAGES                   132
#define IDD_GUI_PPAGE_FMOP              133
#define IDD_GUI_PPAGE_FIRST1            133
#define IDD_GUI_PPAGE_FILTER            133
#define IDC_HAND                        133
#define IDD_GUI_PPAGE_SPECTRUM          133
#define IDD_GUI_PPAGE_ALGO              134
#define IDD_GUI_PPAGE_WAVEFORM          134
#define IDC_SLIDER1                     1000
#define IDC_SLIDER_FREQUENCY            1000
#define IDC_SLIDER_RATIO                1000
#define IDC_STATIC_HISTOGRAM            1000
#define IDC_SLIDER_LENGTH               1000
#define IDC_TEXT1                       1001
#define IDC_SLIDERD1                    1001
#define IDC_LINE_CHART_CTRL             1001
#define IDC_SLIDER_GAIN                 1001
#define IDC_SLIDER_NOISEGAIN            1001
#define IDC_TEXT2                       1002
#define IDC_SLIDERD2                    1002
#define IDC_SLIDER_NL11                 1002
#define IDC_SLIDER_ATTACK               1002
#define IDC_TEXT3                       1003
#define IDC_SLIDERD3                    1003
#define IDC_SLIDER_NL14                 1003
#define IDC_SLIDER_CTRL1                1003
#define IDC_SLIDER_DECAY                1003
#define IDC_TEXT_FREQUENCY              1003
#define IDC_SLIDER2                     1004
#define IDC_SLIDERD4                    1004
#define IDC_SLIDER_NL12                 1004
#define IDC_SLIDER_CTRL2                1004
#define IDC_SLIDER_SUSTAIN              1004
#define IDC_SLIDER3                     1005
#define IDC_TEXT_NL1                    1005
#define IDC_SLIDER_MOD_FREQ             1005
#define IDC_SLIDER_RELEASE              1005
#define IDC_SLIDERD5                    1005
#define IDC_TEXT4                       1006
#define IDC_ABOUT                       1006
#define IDC_LINEAR1                     1006
#define IDC_SLIDER_MOD_DEPTH            1006
#define IDC_SLIDERD6                    1006
#define IDC_SLIDER4                     1007
#define IDC_WAVE_EDIT                   1007
#define IDC_PIPEEDITCTRL                1007
#define IDC_CURVEEDITCTRL1              1007
#define IDC_SLIDER_JETREFLECTION        1007
#define IDC_FFTEDITCTRL                 1007
#define IDC_TEXT5                       1008
#define IDC_TEXT_JETREFLECTION          1008
#define IDC_SLIDER5                     1009
#define IDC_SLIDERL1                    1009
#define IDC_SLIDER_ENDREFLECTION        1009
#define IDC_TEXT6                       1010
#define IDC_SLIDERL2                    1010
#define IDC_TEXT_ENDREFLECTION          1010
#define IDC_SLIDER6                     1011
#define IDC_SLIDERL3                    1011
#define IDC_SLIDER_NL13                 1011
#define IDC_SLIDER_OUTPUTGAIN           1011
#define IDC_TEXT7                       1012
#define IDC_SLIDERL4                    1012
#define IDC_SLIT1                       1012
#define IDC_TEXT_OUTPUTGAIN             1012
#define IDC_SLIDER7                     1013
#define IDC_SLIDER_NL15                 1013
#define IDC_SLIDER_VIBRATOGAIN          1013
#define IDC_SLIDER_OUTPUTGAINTH1        1013
#define IDC_SLIDERL5                    1013
#define IDC_TEXT8                       1014
#define IDC_GRAHAM1                     1014
#define IDC_TEXT_VIBRATOGAIN            1014
#define IDC_TEXT_OUTPUTGAINTH1          1014
#define IDC_SLIDER8                     1015
#define IDC_SLIDER_NL16                 1015
#define IDC_SLIDER_VIBRATOFREQ          1015
#define IDC_SLIDER_OUTPUTGAINTH2        1015
#define IDC_SLIDER_NL17                 1016
#define IDC_TEXT_VIBRATOFREQ            1016
#define IDC_TEXT_OUTPUTGAINTH2          1016
#define IDC_SLIDER_NL18                 1017
#define IDC_TEXT                        1017
#define IDC_SLIDER_OUTPUTGAINTH3        1017
#define IDC_CURVEEDITCTRL               1018
#define IDC_TEXT_OUTPUTGAINTH3          1018
#define IDC_EDIT_NAME                   1019
#define IDC_SLIDER9                     1019
#define IDC_SLIDER_NL1                  1019
#define IDC_EDIT_MAX                    1020
#define IDC_TEXT9                       1020
#define IDC_SLIDER_NL2                  1020
#define IDC_EDIT_MIN                    1021
#define IDC_SLIDER10                    1021
#define IDC_SLIDER_NL3                  1021
#define IDC_TEXT10                      1022
#define IDC_COLORS                      1022
#define IDC_SLIDER_NL4                  1022
#define IDC_NAME                        1023
#define IDC_SLIDER11                    1023
#define IDC_SLIDER_SPEED                1023
#define IDC_SLIDER_NL5                  1023
#define IDC_NAME2                       1024
#define IDC_TEXT11                      1024
#define IDC_LINEAR                      1024
#define IDC_NAME3                       1025
#define IDC_SLIDER12                    1025
#define IDC_HYPERLINK_URL               1025
#define IDC_PLAY                        1025
#define IDC_SLIDER_NL6                  1025
#define IDC_NAME4                       1026
#define IDC_TEXT12                      1026
#define IDC_HYPERLINK_EMAIL             1026
#define IDC_TEXT_RATIO                  1026
#define IDC_SLIDER_NL7                  1026
#define IDC_CHECK_XMEM                  1027
#define IDC_SLIDER13                    1027
#define IDC_TEXT_GAIN                   1027
#define IDC_SLIDER_NL8                  1027
#define IDC_EDIT_VALUE                  1028
#define IDC_BUTTON1                     1028
#define IDC_TEXT_FREQ                   1028
#define IDC_TEXT_ATTACK                 1028
#define IDC_SLIT                        1028
#define IDC_VALUE                       1029
#define IDC_BUTTON2                     1029
#define IDC_TEXT_ALGO                   1029
#define IDC_TEXT_DECAY                  1029
#define IDC_COOK                        1029
#define IDC_CHECK_SUSTAIN               1029
#define IDC_EDIT_RES                    1030
#define IDC_BUTTON3                     1030
#define IDC_TEXT_SUSTAIN                1030
#define IDC_BROWSE                      1030
#define IDC_CHECK_LOG                   1030
#define IDC_CHECK_ZEROCROSSING          1030
#define IDC_CHECK_DATATYPE              1031
#define IDC_BUTTON4                     1031
#define IDC_TEXT_CTRL1                  1031
#define IDC_TEXT_RELEASE                1031
#define IDC_TEXT_BROWSE                 1031
#define IDC_WAVEEDITCTRL                1031
#define IDC_EDIT_INC                    1032
#define IDC_BUTTON5                     1032
#define IDC_TEXT_CTRL2                  1032
#define IDC_APP_NAME                    1032
#define IDC_BUTTON6                     1033
#define IDC_TEXT_MOD_FREQ               1033
#define IDC_AUTHOR                      1033
#define IDC_BUTTON7                     1034
#define IDC_TEXT_MOD_DEPTH              1034
#define IDC_TEXT_L1                     1034
#define IDC_COMPILATION                 1035
#define IDC_BUTTON8                     1035
#define IDC_TEXT_L2                     1035
#define IDC_BUTTON9                     1036
#define IDC_TEXT_NL2                    1036
#define IDC_TEXT_L3                     1036
#define IDC_BUTTON10                    1037
#define IDC_CURVEEDITCTRL2              1037
#define IDC_TEXT_L4                     1037
#define IDC_BUTTON11                    1038
#define IDC_CHECK_EXP                   1038
#define IDC_TEXT_L5                     1038
#define IDC_BUTTON12                    1039
#define IDC_440HZ                       1039
#define IDC_TEXT_D1                     1039
#define IDC_TEXT13                      1040
#define IDC_SAVE                        1040
#define IDC_TEXT_D2                     1040
#define IDC_BUTTON13                    1041
#define IDC_LOAD                        1041
#define IDC_TEXT_D3                     1041
#define IDC_SLIDER14                    1042
#define IDC_LINEAR2                     1042
#define IDC_880HZ                       1042
#define IDC_TEXT_D4                     1042
#define IDC_TEXT14                      1043
#define IDC_FILENAME                    1043
#define IDC_TEXT_D5                     1043
#define IDC_BUTTON14                    1044
#define IDC_SLIT2                       1044
#define IDC_1760HZ                      1044
#define IDC_TEXT_D6                     1044
#define IDC_SLIDER15                    1045
#define IDC_GRAHAM2                     1045
#define IDC_TEXT15                      1046
#define IDC_BUTTON15                    1047
#define IDC_SLIDER16                    1048
#define IDC_TEXT16                      1049
#define IDC_BUTTON16                    1050
#define IDC_SLIDER17                    1051
#define IDC_TEXT17                      1052
#define IDC_BUTTON17                    1053
#define IDC_SLIDER18                    1054
#define IDC_TEXT18                      1055
#define IDC_BUTTON18                    1056
#define IDC_SLIDER19                    1057
#define IDC_TEXT19                      1058
#define IDC_BUTTON19                    1059
#define IDC_SLIDER20                    1060
#define IDC_TEXT20                      1061
#define IDC_BUTTON20                    1062
#define IDC_TEXT_NOISEGAIN              1104
#define IDC_SLIDER_MAXPRESSURE          1105
#define IDC_TEXT_MAXPRESSURE            1106

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        133
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1035
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
